// * CUSTOMIZE COOKIES NAMES
export const COOKIE_AUTHENTICATION_TOKEN_NAME: string = "AUTH_TOKEN";
export const COOKIE_REFRESH_TOKEN_NAME: string = "REFRESH_TOKEN";
export const COOKIE_CSRF_TOKEN_NAME: string = "XSRF_TOKEN";

// * CUSTOMIZE COOKIES EXPIRATIONS
export const COOKIE_AUTHENTICATION_TOKEN_EXPIRATION: number = 60 * 1000 * 15;   // * 15 minutes
export const COOKIE_REFRESH_TOKEN_EXPIRATION: number = 60 * 1000 * 60 * 24 * 7; // * 7 days
export const COOKIE_PUBLIC_CSRF_TOKEN_EXPIRATION: number = 60 * 1000 * 60;      // * 1 hour